### ISSUE TITLE
Start docker on users' demand

### ISSUE THREAD

**Issue by Zerotistic** [Gomez0015/CTF_Cafe#72]
Add a button that any user can click and start a docker to have private instances.
Some recommendations:
* If user click the button again, restart docker. (add a check so that users don't spam the restart ?)
* Docker should be made to always have the least privileges and limit ram consuption.
* They should automatically stop after one hour (show count down on the front for users ?)
* Allow admin to stop/restart instances for a specific challenge (will stop/restart for all users) or for a specific user (will stop/restart all / a specific challenge for a specific user)
* Add the option to generate a random flag for the user when the docker start

Those should be a good start. We might want to add more in the future

**Comment by Gomez0015** [comment]
All Done except point #4

**Comment by Zerotistic** [comment]
Cool!
