### ISSUE TITLE
Multiple Flag

### ISSUE THREAD

**Issue by Kur0n33k0** [Gomez0015/CTF_Cafe#93]
Admin should be able to set multiple flag on a challenge.

Exemple, an OSINT challenge where the flag is the hour with 5 minutes of margin:
The flag is 15h00, admin should be able to set 14h55 - 14h56 .... 15h05

**Comment by Gomez0015** [comment]
Maybe allowing regex flags? So admin could define the flag like this:
Possible Flags: 
FLAG{14:50}
FLAG{14:51}
FLAG{14:52}
FLAG{14:53}
FLAG{14:54}
FLAG{14:55}

Regex Flag:
^FLAG{14:5[0-5]}$

I think would make it easier and better for the admin, what do you think?

**Comment by Gomez0015** [comment]
Done here : acc9d84fb0279d92f60de1f5b10e8791d4685da7
